# -*- coding: utf-8 -*-
"""wavelets_trans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18wxEw81RiR1aM6TNqneIKkuRjE2OCokt
"""

import matplotlib.pyplot as plt
import numpy as np
import pywt
from utils.signal_process import preprocess
import time

def cwt_trans_for_dataset(dataset_X, dataset_Y, save_path, t, scales, wave_name, sampling_period):
    list = [0] * 10
    time0 = time.time()
    for i in range(len(dataset_X)):
        data = dataset_X[i].squeeze()

        fig = cwt_trans(data, t, scales, wave_name, sampling_period)

        x = save_path + str(dataset_Y[i]) + r'/' + str(list[np.argmax(dataset_Y[i])]) + '_' + str(dataset_Y[i]) +'.jpg'
        fig.savefig(x)
        list[np.argmax(dataset_Y[i])] += 1
        plt.close(fig)
        if i % 100 == 0 and i > 0:
            print('已保存{}张cwt图片---{:.2f}'.format(i, time.time() - time0))
            time0 = time.time()
    print('共保存{}张cwt图片'.format(len(dataset_X)))

def cwt_trans(data, t, scales, wave_name, sampling_period, fig=None):
    [cwtmatr, frequencies] = pywt.cwt(data, scales, wave_name, sampling_period)

    # 输出频率计算
    # f = (fs / (n * totalscal)) * np.arange(totalscal, 1, -1)
    #  = scale2frequency(wavelet, scale)/sampling_period

    # 归一化
    # norm_cwtmatr = cwtmatr / np.sqrt(2*np.pi*frequencies.reshape(-1,1))
    is_MyFigureCanvas = False
    if fig is None:
        fig, axs = plt.subplots()
        fig.set_size_inches(864 / 100, 864 / 100)
        # 设置图片和画布、图片和图片的间距
        fig.subplots_adjust(top=1, bottom=0, right=1, left=0, hspace=0, wspace=0)
        # 将当前图形的 X Y轴主刻度设置为空
        axs.xaxis.set_major_locator(plt.NullLocator())
        axs.yaxis.set_major_locator(plt.NullLocator())
        axs.axis('off')
        # 设置或者获取轴域的边界距离（轴两端和画布顶点的距离）
        axs.margins(0, 0)
    else:
        axs = fig.axes[0]
        axs.axis('on')
        axs.set_xlabel('time(s)')
        axs.set_ylabel('frequency(Hz)')
        axs.set_title('cwt_trans')

        is_MyFigureCanvas = True

    axs.contourf(t, frequencies, abs(cwtmatr))
    if is_MyFigureCanvas:
        axs.clabel(plt.contour(t, frequencies, abs(cwtmatr)), inline=True, fontsize=10)
        fig.axes[0] = axs

    return fig

    # plt.contourf(t, frequencies, abs(cwtmatr))
    # plt.axis('off')
    # plt.gcf().set_size_inches(864 / 100, 864 / 100)
    # # 将当前图形的 X Y轴主刻度设置为空
    # plt.gca().xaxis.set_major_locator(plt.NullLocator())
    # plt.gca().yaxis.set_major_locator(plt.NullLocator())
    # # 设置图片和画布、图片和图片的间距
    # plt.subplots_adjust(top=1, bottom=0, right=1, left=0, hspace=0, wspace=0)
    # # 设置或者获取轴域的边界距离（轴两端和画布顶点的距离）
    # plt.margins(0, 0)
    # return plt.gcf()


if __name__ == "__main__":
    path = r'../../datasets/12K_DE_data/3HP'
    train_X, train_Y, valid_X, valid_Y, test_X, test_Y = preprocess.prepro(d_path=path,
                                                                           length=864,
                                                                           number=1000,
                                                                           normal=False,
                                                                           rate=[0.5, 0.25, 0.25],
                                                                           enc=True,
                                                                           enc_step=28)
    all_data_X = np.concatenate((train_X, valid_X, test_X))
    all_data_Y = np.concatenate((train_Y, valid_Y, test_Y))

    # train_X, valid_X, test_X = \
    #     train_X[:, np.newaxis, :], valid_X[:, np.newaxis, :], test_X[:, np.newaxis, :]
    # 添加维度 (7000, 864) -> (7000, 1, 864) [batchsize, input_size, max_length] [批量大小N， 序列长度L, 特征长度Hin]

    N = 864  # 和样本采样长度相同(length=784)
    fs = 12000  # 采样频率，和实际的采样频率相同
    t = np.linspace(0, N / fs, N, endpoint=False)
    wave_name = 'cmor3-3'
    total_scal = 256
    fc = pywt.central_frequency(wave_name)
    cparam = 2 * fc * total_scal  # 常数(n)影响图像分布区域
    scales = cparam / np.arange(total_scal, 1, -1)
    sampling_period = 1.0 / fs
    path = r'../../datasets/cwt_picture/cmor3-3_10000_3HP/'

    cwt_trans_for_dataset(all_data_X, all_data_Y, path, t, scales, wave_name, sampling_period)

    # path_train = r'../../datasets/cwt_picture/0HP/cmor3-3/train/'
    # path_valid = r'../../datasets/cwt_picture/0HP/cmor3-3/valid/'
    # path_test = r'../../datasets/cwt_picture/0HP/cmor3-3/test/'
    #
    # cwt_trans_for_dataset(train_X, train_Y, path_train, t, scales, wave_name, sampling_period)
    # cwt_trans_for_dataset(valid_X, valid_Y, path_valid, t, scales, wave_name, sampling_period)
    # cwt_trans_for_dataset(test_X, test_Y, path_test, t, scales, wave_name, sampling_period)
